name = "P3109csvs"
uuid = "948f2f6d-415c-494a-a467-84f73c1ab52f"
author = "Jeffrey Sarnoff <jeffrey.sarnoff@ieee.org>"
version = "0.1.0"

[deps]
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"

[compat]
Tables = "1.11"
CSV = "0.10 - 0.50"
julia = "1.11"
